"""add default_branch to repositories

Revision ID: 394f452fcb07
Revises: ceedab77b8b8
Create Date: 2026-05-21 00:16:46.798713
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '394f452fcb07'
down_revision: str | None = 'ceedab77b8b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('default_branch', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'default_branch')
    # ### end Alembic commands ###
