"""create initial tables

Revision ID: ceedab77b8b8
Revises: 
Create Date: 2026-05-20 22:58:03.326789
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ceedab77b8b8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('encrypted_github_token', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("last_sync_status IN ('pending', 'syncing', 'success', 'failed')", name='ck_repositories_last_sync_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_repo_id', name='uq_repositories_user_repo')
    )
    op.create_index('ix_repositories_user_id', 'repositories', ['user_id'], unique=False)
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_type IN ('github_user', 'git_email')", name='ck_contributors_source_type'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'github_login', 'email', name='uq_contributors_repo_identity')
    )
    op.create_index('ix_contributors_repo_email', 'contributors', ['repo_id', 'email'], unique=False)
    op.create_index('ix_contributors_repo_id', 'contributors', ['repo_id'], unique=False)
    op.create_index('ix_contributors_repo_login', 'contributors', ['repo_id', 'github_login'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('author_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('committer_name', sa.String(length=255), nullable=True),
    sa.Column('committer_email', sa.String(length=255), nullable=True),
    sa.Column('committer_login', sa.String(length=255), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'sha', name='uq_commits_repo_sha')
    )
    op.create_index('ix_commits_repo_author', 'commits', ['repo_id', 'author_login'], unique=False)
    op.create_index('ix_commits_repo_date', 'commits', ['repo_id', 'committed_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('author_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('labels', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number', name='uq_issues_repo_number')
    )
    op.create_index('ix_issues_repo_closed', 'issues', ['repo_id', 'closed_at'], unique=False)
    op.create_index('ix_issues_repo_created', 'issues', ['repo_id', 'created_at'], unique=False)
    op.create_index('ix_issues_repo_state', 'issues', ['repo_id', 'state'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('is_merged', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('author_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('draft', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number', name='uq_pull_requests_repo_number')
    )
    op.create_index('ix_prs_repo_created', 'pull_requests', ['repo_id', 'created_at'], unique=False)
    op.create_index('ix_prs_repo_merged', 'pull_requests', ['repo_id', 'merged_at'], unique=False)
    op.create_index('ix_prs_repo_state', 'pull_requests', ['repo_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prs_repo_state', table_name='pull_requests')
    op.drop_index('ix_prs_repo_merged', table_name='pull_requests')
    op.drop_index('ix_prs_repo_created', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('ix_issues_repo_state', table_name='issues')
    op.drop_index('ix_issues_repo_created', table_name='issues')
    op.drop_index('ix_issues_repo_closed', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_commits_repo_date', table_name='commits')
    op.drop_index('ix_commits_repo_author', table_name='commits')
    op.drop_table('commits')
    op.drop_index('ix_contributors_repo_login', table_name='contributors')
    op.drop_index('ix_contributors_repo_id', table_name='contributors')
    op.drop_index('ix_contributors_repo_email', table_name='contributors')
    op.drop_table('contributors')
    op.drop_index('ix_repositories_user_id', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
